
\newglossaryentry{CTAO}{
    name={CTAO}, 
    description={The Cherenkov Telescope Array Observatory, an international user facility distributed over four primary sites: a Headquarters, Science Data Management Centre, and two array-sites in the norhtern and southern hemispheres: CTA-N and CTA-S. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28184}{CTA-GLOS-206}})}
}

\newglossaryentry{CTA North}{
    name={CTA North}, 
    description={CTA Observation site hosting an Array of Cherenkov Telescopes, in the Northern Hemisphere. The selected CTA North site is Observatorio del Roque de los Muchachos (ORM), La Palma, Spain. CTA North may be abbreviated as CTA-N. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28185}{CTA-GLOS-207}})}
}

\newglossaryentry{CTA South}{
    name={CTA South}, 
    description={CTA Observation site hosting an Array of Cherenkov Telescopes, in the Southern Hemisphere. The selected CTA South site is lies between the locations of the Paranal and Armazones ESO telescope sites in Chile. CTA South may be abbreviated as CTA-S. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28186}{CTA-GLOS-208}})}
}

\newglossaryentry{Headquarters}{
    name={Headquarters}, 
    description={The primary centre for CTAO governance, administration and management. The selected site for the CTA Headquarters (HQ) is Bologna, Italy. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28187}{CTA-GLOS-209}})}
}

\newglossaryentry{SDMC}{
    name={SDMC}, 
    description={(Science Data Management Centre) The primary centre for the management of CTA data products and science user support including proposal handling. The selected site for the CTA Science Data Management Centre (SDMC) is Zeuthen, Germany. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28188}{CTA-GLOS-210}})}, 
    first={Science Data Management Centre (SDMC)}, 
}

\newglossaryentry{Array Site}{
    name={Array Site}, 
    description={One of the two observation sites, CTA-N or CTA-S. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28189}{CTA-GLOS-211}})}
}

\newglossaryentry{System}{
    name={System}, 
    description={The word system is used at multiple levels in the CTAO heirachy to refer to an element implemented in hardware or software or both that performs a function or functions identified in the design of CTAO. CTAO is therefore a System of Systems. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28190}{CTA-GLOS-212}})}
}

\newglossaryentry{Array}{
    name={Array}, 
    description={All of the Cherenkov Telescopes at one of the Observatory Sites. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28191}{CTA-GLOS-213}})}
}

\newglossaryentry{Sub-array}{
    name={Sub-array}, 
    description={A sub-set of the Cherenkov Telescopes at one of the Array Sites. May be qualified by a Cherenkov Telescope type (LST, MST, SST) to denote the sub-set of all telescopes of that type on a given site. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28192}{CTA-GLOS-214}})}
}

\newglossaryentry{Array Element}{
    name={Array Element}, 
    description={A system deployed on an Array Site which is needed for the scientific operation of CTA and which is interfaced to the ACADA and SAS systems. Array Elements (and in cases of sufficient complexity, such as that of a Cherenkov Telescope, also their sub-systems) are required to implement well-defined common States. An Array Element consists of one or more Controllable Systems and may also include Sensors, plus a software system to manage these elements. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28193}{CTA-GLOS-215}})}
}

\newglossaryentry{Cherenkov Telescope}{
    name={Cherenkov Telescope}, 
    description={A system composed of a Cherenkov Camera and Telescope Structure which is used to collect and image Cherenkov light from Air Showers. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28194}{CTA-GLOS-216}})}
}

\newglossaryentry{Telescope Structure}{
    name={Telescope Structure}, 
    description={All of the hardware and software associated to a single optical telescope capable of pointing to different parts of the sky and collecting light on to a  Cherenkov Camera . A Telescope Structure forms part of a  Cherenkov Telescope  System. Telescope Structure may be abbreviated as 'Structure'. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28195}{CTA-GLOS-217}})}
}

\newglossaryentry{Cherenkov Camera}{
    name={Cherenkov Camera}, 
    description={All of the hardware and software associated with Cherenkov image detection, digitisation, transmission and pre-processing. A Cherenkov Camera forms part of a  Cherenkov Telescope  System, and has as its principle elements a Camera Unit and software deployed on a Camera Server. Cherenkov Camera may be abbreviated as 'Camera'. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28196}{CTA-GLOS-218}})}
}

\newglossaryentry{Camera Unit}{
    name={Camera Unit}, 
    description={The part of a Cherenkov Camera that can be mounted and umounted from a Telescope Structure and tested in the Camera Test Facility at a CTA Array Site. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28197}{CTA-GLOS-219}})}
}

\newglossaryentry{Controllable System}{
    name={Controllable System}, 
    description={A system on an Array Site consisting of hardware elements, a Local Control System (LCS) at the location of the hardware, and a software component (the LCS Controller) running on the on-site data centre. Controllable Systems implement standard interfaces to the ACADA and/or SAS systems and are integrated in to Array Elements for the purpose of science operations, but independently controllable for engineering purposes / technical operations. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28198}{CTA-GLOS-220}})}
}

\newglossaryentry{Sensors}{
    name={Sensors}, 
    description={A data collecting instrument plus an associated software component which delivers information to the ACADA or SAS via a standard interface. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28199}{CTA-GLOS-221}})}
}

\newglossaryentry{Interface Cabinet}{
    name={Interface Cabinet}, 
    description={A permanent installation close to each Cherenkov Telescope, or other Array Element with comparable needs, which serves as the main interface point for power and network between a Telescope and central services as well as supporting local maintainence and engineering work and interfacing local to array-level safety systems. The Interface Cabinets at an Array Site form part of the on-site Infrastructure. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28200}{CTA-GLOS-222}})}
}

\newglossaryentry{LST}{
    name={LST}, 
    description={(Large Sized Telescope) A type of Cherenkov Telescope present on both CTA array sites with focus on the low energy range of CTA. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28201}{CTA-GLOS-223}})}, 
    first={Large Sized Telescope (LST)}, 
}

\newglossaryentry{MST}{
    name={MST}, 
    description={(Medium Sized Telescope) A type of Cherenkov Telescope present on both CTA array sites with focus on the medium energy range of CTA. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28202}{CTA-GLOS-224}})}, 
    first={Medium Sized Telescope (MST)}, 
}

\newglossaryentry{SST}{
    name={SST}, 
    description={(Small Sized Telescope) A type of Cherenkov Telescope present on the Southern CTA array site with focus on the high energy range of CTA. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28203}{CTA-GLOS-225}})}, 
    first={Small Sized Telescope (SST)}, 
}

\newglossaryentry{CTF}{
    name={CTF}, 
    description={(Camera Test Facility) Facility installed at one of the CTA Array Sites that can be used for a detailed evaluation of the performance of a Camera Unit of any of the types present on a given Array Site. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28204}{CTA-GLOS-226}})}, 
    first={Camera Test Facility (CTF)}, 
}

\newglossaryentry{ACADA}{
    name={ACADA}, 
    description={(Array Control and Data Acquisition). A software system responsible for the control and monitoring of telescopes and auxiliary (non-telescope) instruments at a CTA site, for the efficient scheduling and execution of pre-scheduled observations and those triggered dynamically, for the monitoring of the system performance, for the data acquisition and volume reduction as well as the automatic generation of science alerts. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28942}{CTA-GLOS-245}})}, 
    first={Array Control and Data Acquisition (ACADA)}, 
}

\newglossaryentry{DPPS}{
    name={DPPS}, 
    description={(Data Processing and Preservation System) A software system responsible for producing the science data products given to Science Users; including therefore the production and analysis of simulation data, (re)processing and the long-term preservation of data products and related information that will facilitate reproducibility as well as their transfer from the array sites. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28943}{CTA-GLOS-246}})}, 
    first={Data Processing and Preservation System (DPPS)}, 
}

\newglossaryentry{SUSS}{
    name={SUSS}, 
    description={(Science User Support System) A software system providing the main point of access for proposal submission and to high-level CTA data products and corresponding sets of CTA tools to support data analysis. Provides means for proposal evaluation, for generation of the long-term schedule and for user support. Also includes outreach services. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28944}{CTA-GLOS-247}})}, 
    first={Science User Support System (SUSS)}, 
}

\newglossaryentry{OSS}{
    name={OSS}, 
    description={(Operations Support System) A collection of software systems supporting CTA operations. Includes configuration management, issue tracking, maintenance planning, authentication and authorisation systems. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28945}{CTA-GLOS-248}})}, 
    first={Operations Support System (OSS)}, 
}

\newglossaryentry{SAS}{
    name={SAS}, 
    description={(Safety and Alarm System) The hardware and software system for monitoring and control of the primary safety-relevant aspects (incl. interlocks) of the Telescopes and Infrastructure elements at a CTA array site. Includes an integrated alarm system. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28946}{CTA-GLOS-249}})}, 
    first={Safety and Alarm System (SAS)}, 
}

\newglossaryentry{MAS}{
    name={MAS}, 
    description={(Management and Administration System) A collection of software systems associated with the administration of CTA. Includes procurement, logistics, human resources management, and systems supporting the generation of performance/status reports for external stakeholders. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28947}{CTA-GLOS-250}})}, 
    first={Management and Administration System (MAS)}, 
}

\newglossaryentry{ACE}{
    name={ACE}, 
    description={(Array Common Elements) Array Elements, Controllable Systems and/or Sensors that are located at one of the array sites for the purposes of supporting centrally co-ordinated calibration and environmental monitoring activities. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=30990}{CTA-GLOS-296}})}, 
    first={Array Common Elements (ACE)}, 
}

\newglossaryentry{Central Computer Time Synchronisation System}{
    name={Central Computer Time Synchronisation System}, 
    description={Centrally provided NTP-based timing System designed to provide timing information for the purposes of general activities such as logging. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=30738}{CTA-GLOS-294}})}
}

\newglossaryentry{Central Precision Time Synchronisation System}{
    name={Central Precision Time Synchronisation System}, 
    description={Centrally provided WR-based Timing Distribution System designed to keep clocks in sync to sub-ns precision for Cherenkov Event Timing purposes. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=30739}{CTA-GLOS-295}})}
}

\newglossaryentry{Local Mode}{
    name={Local Mode}, 
    description={Mode of operation of a field-deployed Controllable System activated and deactivated by a person physically present at the Interface Cabinet associated with the system. Whilst in Local Mode all remote actions that could endanger the safety of a  local person are prevented. Local Mode supports engineering and maintenance activities. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28473}{CTA-GLOS-233}})}
}

\newglossaryentry{Remote Mode}{
    name={Remote Mode}, 
    description={Mode of operation of a Controllable System to allow control by a person not present at the Array Element Location, available when not disabled at the Interface Cabinet. Remote mode supports observatory science operation and system/array-level engineering activities. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28472}{CTA-GLOS-232}})}
}

\newglossaryentry{Safe State}{
    name={Safe State}, 
    description={The System is in a configuration suitable for survival in extreme conditions, minimising use of power whilst still providing basic status monitoring, and maximising the instrument lifetime. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28474}{CTA-GLOS-234}})}
}

\newglossaryentry{Observing State}{
    name={Observing State}, 
    description={The System is in a state associated with observatory data taking, with configuration dictated by performance requirements. Calibration activities may take place. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28475}{CTA-GLOS-235}})}
}

\newglossaryentry{Off State}{
    name={Off State}, 
    description={The System is entirely without electrical power. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28476}{CTA-GLOS-236}})}
}

\newglossaryentry{Ready State}{
    name={Ready State}, 
    description={The System is prepared for rapid entry in to the Observing State. Internal calibration activities may take place. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28477}{CTA-GLOS-237}})}
}

\newglossaryentry{Standby State}{
    name={Standby State}, 
    description={The System is in a state which is still safe with respect to extreme conditions, but has all components activated, with preparations for Observation initiated. Internal calibration activities may take place. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28478}{CTA-GLOS-238}})}
}

\newglossaryentry{Fault State}{
    name={Fault State}, 
    description={The System has encountered a serious problem which means it is currently unable to maintain or reach any of the standard States. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28479}{CTA-GLOS-239}})}
}

\newglossaryentry{Engineering State}{
    name={Engineering State}, 
    description={The System is in a state designed to facilitate maintenance and engineering activities, and is unavailable for scientific operations. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28480}{CTA-GLOS-240}})}
}

\newglossaryentry{Science Operations Mode}{
    name={Science Operations Mode}, 
    description={Operational Mode of the ACADA suitable for Science Observations. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=30016}{CTA-GLOS-277}})}
}

\newglossaryentry{Technical Operations Mode}{
    name={Technical Operations Mode}, 
    description={Operational Mode of the ACADA suitable for maintenance and engineering activities, with basic monitoring ongoing, corresponding to typical day-time operations. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=30017}{CTA-GLOS-278}})}
}

\newglossaryentry{raw internal}{
    name={raw internal}, 
    description={(R0) On-site streamed raw data, not normally preserved long-term in this form. R0 content and format is internal to each device / controllable system, such as raw data transmitted from the physical device / system to its respective server in the on-site Data Centre. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28995}{CTA-GLOS-258}})}, 
    first={R0 (raw internal)}, 
}

\newglossaryentry{raw common}{
    name={raw common}, 
    description={(R1) On-site stream raw data meeting common standards, transmitted on-site from a  Camera  or other on-site system to the  ACADA . This is the first level of data seen by the ACADA, that will typically need some pre-processing from the R0 data format. Exceptionally, some R1 data may be stored for engineering purposes. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28996}{CTA-GLOS-259}})}, 
    first={R1 (raw common)}, 
}

\newglossaryentry{raw archived}{
    name={raw archived}, 
    description={(DL0) All archival data from the data acquisition hardware/software, transmitted from the ACADA to the DPPS. This is the lowest level of data that are intended for long-term storage in the bulk archive. This includes both camera event data and technical data from other sub-systems, such as non-camera devices or software. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28997}{CTA-GLOS-260}})}, 
    first={DL0 (raw archived)}, 
}

\newglossaryentry{processed}{
    name={processed}, 
    description={(DL1) Processed DL0 data that may include telescope-level (TEL) data and parameters derived from them. Typical contents include calibrated image charge, Hillas parameters, and a usable telescope pattern. DL1 data is not normally stored long-term. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28998}{CTA-GLOS-261}})}, 
    first={DL1 (processed)}, 
}

\newglossaryentry{reconstructed}{
    name={reconstructed}, 
    description={(DL2) Reconstructed shower parameters such as energy, direction, particle ID, and related signal discrimination parameters. Does not include telescope-level (TEL) information. For each event this information may be repeated for multiple reconstruction and discrimination methods. DL2 data is not normally stored long-term. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28999}{CTA-GLOS-262}})}, 
    first={DL2 (reconstructed)}, 
}

\newglossaryentry{reduced}{
    name={reduced}, 
    description={(DL3) Sets of selected events with a single final set of reconstruction and discrimination parameters, along with associated instrumental response characterisations together with their periods of validity, and any technical data needed for science analysis. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=29000}{CTA-GLOS-263}})}, 
    first={DL3 (reduced)}, 
}

\newglossaryentry{binned}{
    name={binned}, 
    description={(DL4) Data product produced by binning of DL3 data, including data cubes and maps which are suitable for combination/summation to produce DL5 products. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=29001}{CTA-GLOS-264}})}, 
    first={DL4 (binned)}, 
}

\newglossaryentry{science}{
    name={science}, 
    description={(DL5) Data product produced by combination of DL4 products an extraction target specific region(s) of interest. Includes for example light-curves and spectra, along with associated data such as source models and fit results. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=29002}{CTA-GLOS-265}})}, 
    first={DL5 (science)}, 
}

\newglossaryentry{high-level}{
    name={high-level}, 
    description={(DL6) High-level or legacy observatory data, such as survey maps and source catalogues. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31250}{CTA-GLOS-356}})}, 
    first={DL6 (high-level)}, 
}

\newglossaryentry{Observation Conditions}{
    name={Observation Conditions}, 
    description={Environmental conditions under which full operation of the CTA System must be possible without incurring damage. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28962}{CTA-GLOS-253}})}
}

\newglossaryentry{Precision Pointing Conditions}{
    name={Precision Pointing Conditions}, 
    description={Environmental conditions under which it is expected that the optimum pointing precision of the CTA System can be achieved. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28963}{CTA-GLOS-254}})}
}

\newglossaryentry{Normal Conditions}{
    name={Normal Conditions}, 
    description={Environmental conditions under which standard operation, engineering and maintenance activities may be undertaken, during day or night. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28966}{CTA-GLOS-257}})}
}

\newglossaryentry{Transition Conditions}{
    name={Transition Conditions}, 
    description={Environmental conditions under which environmental parameters may exceed those of the observing state, whilst the system transitions into a safe state. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28964}{CTA-GLOS-255}})}
}

\newglossaryentry{Survival Conditions}{
    name={Survival Conditions}, 
    description={Environmental conditions expected to occur with a probability of roughly 2\% per annum at each array site. The level of damage incurred under survival conditions must not exceed the serviceability limit state. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28965}{CTA-GLOS-256}})}
}

\newglossaryentry{Serviceability Limit}{
    name={Serviceability Limit}, 
    description={Damage can be repaired in-situ using available spare parts and a normal level of on-site manpower. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28951}{CTA-GLOS-251}})}
}

\newglossaryentry{Collapse Prevention Limit}{
    name={Collapse Prevention Limit}, 
    description={The structure is heavily damaged, with very limited residual strength and stiffness, yet retains structural integrity and resists collapse. Repairs may require additional resources beyond those usually available on-site. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28952}{CTA-GLOS-252}})}
}

\newglossaryentry{Sky}{
    name={Sky}, 
    description={(Pedestal) The mean digital signal derived in the absence of transient illumination yet in the presence of continuous background light (NSB) contributions. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=27931}{CTA-GLOS-183}})}, 
    first={Pedestal (Sky)}, 
}

\newglossaryentry{Dark Pedestal}{
    name={Dark Pedestal}, 
    description={The mean digital signal extracted from a Camera pixel in the complete absence of incident light. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=27932}{CTA-GLOS-184}})}
}

\newglossaryentry{Electronic Pedestal}{
    name={Electronic Pedestal}, 
    description={The mean digital signal extracted from a Camera pixel with photosensors inactive. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=27933}{CTA-GLOS-185}})}
}

\newglossaryentry{Triggering}{
    name={Triggering}, 
    description={(Triggering) Identification by a Cherenkov Camera of a block of time for which data may be of interest for analysis and to which a Trigger Timestamp can be associated. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=27934}{CTA-GLOS-186}})}, 
    first={Triggering (Camera)}, 
}

\newglossaryentry{Internal Trigger}{
    name={Internal Trigger}, 
    description={Triggering of a Camera due to a flash of light. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=27935}{CTA-GLOS-187}})}
}

\newglossaryentry{External Trigger}{
    name={External Trigger}, 
    description={Triggering of a Camera due to an instruction received from Camera firmware, software or from the central control system. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=27936}{CTA-GLOS-188}})}
}

\newglossaryentry{Trigger Timestamp}{
    name={Trigger Timestamp}, 
    description={Absolute time plus auxiliary information associated with a Camera Event. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=27937}{CTA-GLOS-189}})}
}

\newglossaryentry{Camera Event}{
    name={Camera Event}, 
    description={Set of data from the pixels of a Cherenkov Camera associated with a Trigger and including time and amplitude information. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=27938}{CTA-GLOS-190}})}
}

\newglossaryentry{Camera}{
    name={Camera}, 
    description={(Image) A data product resulting from processing of a Camera Event that contains a single value per pixel. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=27939}{CTA-GLOS-191}})}, 
    first={Image (Camera)}, 
}

\newglossaryentry{Local Event}{
    name={Local Event}, 
    description={Camera Event that is flagged as requested for long-term storage by a Camera, independently of whether it is an Array-Level Event. Local Events are typically of interest for calibration, monitoring or engineering purposes. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28370}{CTA-GLOS-230}})}
}

\newglossaryentry{cFoV}{
    name={cFoV}, 
    description={(Camera Field of View) The Field of View of a CTA Camera is defined as twice the average angular distance of the centre of gravity of all  Camera Pixel  centres (i.e. the Camera centre) to the centre of all Edge Pixels. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=27943}{CTA-GLOS-195}})}, 
    first={Camera Field of View (cFoV)}, 
}

\newglossaryentry{Edge Pixel}{
    name={Edge Pixel}, 
    description={Edge pixels are those pixels lying outside of 85\% of the required FoV radius that have fewer nearest neighbouring pixels than flat sides, in the directions perpendicular to their flat sides and within tolerances large enough to account for rounding errors and distortions. The distance of a nearest neighbour must be less than half the average angular pixel pitch, such that there is a maximum of one nearest neighbour per flat side ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=27945}{CTA-GLOS-197}})}
}

\newglossaryentry{Pixel Pitch}{
    name={Pixel Pitch}, 
    description={The average angular distance between the centres of two immediately adjacent pixels, measured using the effective focal length. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=27946}{CTA-GLOS-198}})}
}

\newglossaryentry{Broken Pixel}{
    name={Broken Pixel}, 
    description={A Pixel which is not available to perform signal amplitude and/or time measurements with the required performance. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=27948}{CTA-GLOS-200}})}
}

\newglossaryentry{Data Volume Reduction}{
    name={Data Volume Reduction}, 
    description={Processing that allows Camera Event data to be stored more compactly without significant loss of information, and hence without significant impact on the sensitivity of an array or sub-array. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=27942}{CTA-GLOS-194}})}
}

\newglossaryentry{Deadtime}{
    name={Deadtime}, 
    description={Any period of inability of a Cherenkov Camera to trigger on or produce data for  Events  that is shorter than 0.5 seconds. Longer periods should be considered as unavailability rather than deadtime. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31276}{CTA-GLOS-357}})}
}

\newglossaryentry{PSF}{
    name={PSF}, 
    description={() The optical point-spread-function (PSF), as measured in the telescope focal plane, describes the response of the optical system to a point-like source of light. In general, this is a function of the position within the field of view and the pointing direction of the telescope and is affected by the environmental conditions. The optical PSF is typically characterised by the 80\% angular light containment diameter  Theta\_80 . ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=27949}{CTA-GLOS-201}})}, 
    first={ (PSF)}, 
}

\newglossaryentry{Theta_80}{
    name={Theta_80}, 
    description={Theta\_80 (  80 ) is the standard parameter for characterising the  optical PSF  of a telescope. It is the opening angle (diameter) relative to the light centroid at a specific place within the focal plane, within which 80 percent of those photons that are reflected into a 1 o  diameter circle on the camera fall. Unless otherwise specified, the source of light should be assumed to be at infinity. Photons in the wavelength range 300 - 550 nm with the  Cherenkov Reference Spectrum . Operating Illumination should be assumed. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=27950}{CTA-GLOS-202}})}
}

\newglossaryentry{Mirror Reflectivity}{
    name={Mirror Reflectivity}, 
    description={The fraction of photons incident on an optical element (facet) of a reflector dish, that are focussed into the required cFoV. The mirror reflectivity does not include any effects from shadowing by, for example, the support structure of either incoming or outgoing light. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=27952}{CTA-GLOS-204}})}
}

\newglossaryentry{Geometrical Mirror Area}{
    name={Geometrical Mirror Area}, 
    description={It is the projected area of the primary mirror multiplied by (1-f), where f is the fraction of photons lost due to shadowing (for example by support structures, secondary mirror, camera etc.). The geometrical mirror area is generally a function of the position within the field of view. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=29839}{CTA-GLOS-272}})}
}

\newglossaryentry{Effective Mirror Area}{
    name={Effective Mirror Area}, 
    description={The effective mirror area characterises the light-collection power of the optical system. This quantity is the average of the product of the  Geometrical Mirror Area  and the mirror reflectivity weighted, in the range 300-550nm, by the  Cherenkov Reference Spectrum . The effective mirror area is generally a function of the position within the field of view. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=29840}{CTA-GLOS-273}})}
}

\newglossaryentry{Optical Efficiency}{
    name={Optical Efficiency}, 
    description={The overall optical efficiency of the system for signal photons,  sig  , is defined as:         where  F ( ) is the nominal  Cherenkov Reference Spectrum  and  is the probability that a photon of a given wavelength, incident on the primary mirror and parallel with the optical axis, results in the generation of a detectable photoelectron. This efficiency therefore includes the reflectivity of the mirrors, of light concentrators if present, camera dead space and the quantum and collection efficiencies of photosensors.    The optical efficiency for background,  bg  , is defined in an identical way but with  F ( ) replaced by the  Background Light Reference Spectrum . ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=29399}{CTA-GLOS-268}})}
}

\newglossaryentry{Astrometric Accuracy}{
    name={Astrometric Accuracy}, 
    description={The accuracy with which a physical position on the focal surface can be mapped to a celestial coordinate in off-line analysis, averaged over the required field of view and expressed as the root-mean-square space-angle deviation from the true value over all pixels, averaging over a timescale of 1 minute. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=29998}{CTA-GLOS-274}})}
}

\newglossaryentry{Post-Calibration Astrometric Accuracy}{
    name={Post-Calibration Astrometric Accuracy}, 
    description={Astrometric Accuracy  achieved after application of full calibration procedure applied as part of the routine production of DL3 data ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=29999}{CTA-GLOS-275}})}
}

\newglossaryentry{Online Astrometric Accuracy}{
    name={Online Astrometric Accuracy}, 
    description={Astrometric Accuracy  achieved online using fast calibration procedures applied as part of the production of DL0 data ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=30013}{CTA-GLOS-276}})}
}

\newglossaryentry{Differential Sensitivity}{
    name={Differential Sensitivity}, 
    description={The Differential Sensitivity is the minimum detectable flux in five independent bins per decade in reconstructed energy. The required level of confidence in each bin is a five standard deviation (5 ) statistical significance (calculated with equation 17 from Li & Ma 1983, ApJ 272, 317) and the presence of at least 10 excess events above background. We also require that the signal excess is at least five times the assumed rms background systematic uncertainty of 1\% of the background remaining after cuts. Unless otherwise specified  Reference Conditions  should be assumed. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31182}{CTA-GLOS-354}})}
}

\newglossaryentry{Energy Resolution}{
    name={Energy Resolution}, 
    description={A measure of how well an array or sub-array in a given configuration can reconstruct the energy of a primary particle. Unless otherwise specified the primary should be assumed to be a gamma-ray. The energy resolution is defined such that 68\% of particles will have a true energy within this  E of their reconstructed/estimated energy. It is derived from simulations via the energy dispersion matrix, after all appropriate selection cuts. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31148}{CTA-GLOS-352}})}
}

\newglossaryentry{Angular Resolution}{
    name={Angular Resolution}, 
    description={A measure of how well the reconstructed direction of a primary particle corresponds to the true arrival direction. Unless otherwise specified the primary particle should be assumed to be a gamma-ray. The angular resolution is defined as the opening angle of 68\% containment for the angular distance to the true direction. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31151}{CTA-GLOS-353}})}
}

\newglossaryentry{gFoV}{
    name={gFoV}, 
    description={(Gamma-ray Field of View) The Gamma-ray Field of View of a CTA array or sub-array is defined as twice the angular offset from the array or sub-array pointing direction at which the differential point-source sensitivity (for a 50 hour exposure) is degraded by a factor of two.  Note that the gamma-ray FoV is an energy- and analysis-dependent quantity. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=27944}{CTA-GLOS-196}})}, 
    first={Gamma-ray Field of View (gFoV)}, 
}

\newglossaryentry{Collection}{
    name={Collection}, 
    description={(Effective  Area) The energy-dependent effective collection area of an array or sub-array is defined as the number of selected gamma-rays in a given observation time divided by the incident flux and observation time. Unless otherwise specified, the Effective Area should be assumed to include all quality and background rejection cuts, including angular cuts associated with a point-source analysis. Effective Area may be given as a function of either true or reconstructed primary energy. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=27951}{CTA-GLOS-203}})}, 
    first={Effective  Area (Collection)}, 
}

\newglossaryentry{Cherenkov Reference Spectrum}{
    name={Cherenkov Reference Spectrum}, 
    description={Spectral form of the Cherenkov light from air showers arriving at ground level that should be assumed for calculations (see attachment - which also shows the  Background Light Reference Spectrum ). ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28367}{CTA-GLOS-228}})}
}

\newglossaryentry{Background Light Reference Spectrum}{
    name={Background Light Reference Spectrum}, 
    description={Spectral form of the night sky background light that should be assumed for calculations unless otherwise specified (see attachment - which also shows the  Cherenkov Reference Spectrum ). Note that a  modified spectrum  is appropriate for moonlight conditions. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28364}{CTA-GLOS-227}})}
}

\newglossaryentry{Moonlight Reference Spectrum}{
    name={Moonlight Reference Spectrum}, 
    description={Spectral form for the brightness of the night sky that should be assumed for calculations under moonlight conditions - see orange curve in attached figure and spectra points in attached data file. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31124}{CTA-GLOS-351}})}
}

\newglossaryentry{Reference Proton Flux}{
    name={Reference Proton Flux}, 
    description={The Reference Proton Flux at the top of the atmosphere is given by the expression  dN/dE  = 9.8 x 10 -6  ( E /TeV) -2.62  TeV -1  s -1  cm -2  sr -1 . Where  E  is the energy of primary cosmic protons. Isotropy can be assumed and unless otherwise indicated an observation zenith angle of 20 degrees should be assumed. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28381}{CTA-GLOS-231}})}
}

\newglossaryentry{Reference Electron Flux}{
    name={Reference Electron Flux}, 
    description={The Reference Electron Flux at the top of the atmosphere is given by the expression  dN/dE  = 2.385 x 10 -9 ( E /TeV) -3.34  (1+1.95*(exp( G (log 10 ( E /TeV))-1) TeV -1  s -1  cm -2  sr -1 . Where  E  is the energy of primary cosmic electrons and  G  is a Gaussian function with mean=-0.101 and sigma=0.741. Isotropy can be assumed. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31189}{CTA-GLOS-355}})}
}

\newglossaryentry{Reference Gamma-ray Flux}{
    name={Reference Gamma-ray Flux}, 
    description={The Reference Gamma-ray Flux at the top of the atmosphere is given by the expression  dN/dE  = 2.83 x 10 -11  ( E /TeV) -2.62  TeV -1  s -1  cm -2 . Where  E  is the energy of primary gamma-rays. Point-like emission and an observation zenith angle of 20 degrees should be assumed unless otherwise indicated. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28926}{CTA-GLOS-244}})}
}

\newglossaryentry{Reference Conditions}{
    name={Reference Conditions}, 
    description={The standard set of conditions to be used for performance comparison using simulations (unless otherwise specified) is:     	 20 degree zenith angle observations.  	 A night sky background flux of 0.24 photons/ns/sr/cm 2  in the wavelength range from 300-650 nm (corresponding approximately to the extragalactic night sky background level during astronomical darkness), following the  Background Light Reference Spectrum .  	 50\% of the time pointing exactly North and and 50\% to the South.      An on-axis point-like source can be assumed unless otherwise specified. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=29010}{CTA-GLOS-266}})}
}

\newglossaryentry{Proposal}{
    name={Proposal}, 
    description={A scientific project proposed to the Observatory and assigned a unique identifier. A Proposal contains the list of  Scientific Targets  to be observed and associated constraints in terms of configurations, environmental conditions, observation times and external pre-conditions. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=30019}{CTA-GLOS-280}})}
}

\newglossaryentry{Science Target}{
    name={Science Target}, 
    description={A Science Target is a celestial object or region of interest which is to be observed to address the scientific case of a  Proposal ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=30020}{CTA-GLOS-281}})}
}

\newglossaryentry{Merged Target}{
    name={Merged Target}, 
    description={A region of interest suitable for sub-array Observations to address the scientific case of one or more  Proposals , defined by the merger of  Science Targets  as appropriate. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=30021}{CTA-GLOS-282}})}
}

\newglossaryentry{Telescope}{
    name={Telescope}, 
    description={(Target) A fixed celestial direction, horizon system direction, or defined trajectory to which the optical axis of a  Telescope  should be aligned. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=30022}{CTA-GLOS-283}})}, 
    first={Target (Telescope)}, 
}

\newglossaryentry{Observation Block}{
    name={Observation Block}, 
    description={The smallest scheduling unit, a continuous observation with a sub-array during which science data is collected on the  Merged Target  of the parent  Scheduling Block . During Observation Blocks, the Camera configuration and  Telescope Target  remain fixed. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=30023}{CTA-GLOS-284}})}
}

\newglossaryentry{Scheduling Block}{
    name={Scheduling Block}, 
    description={A set of  Observation Blocks  for the same sub-array, scheduled contiguously with a single  Merged Target .  Telescope Targets  for Observation Blocks are generated from  Proposals  based on the specified observing strategy. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=30024}{CTA-GLOS-285}})}
}

\newglossaryentry{Science}{
    name={Science}, 
    description={(Observation) An Observation is the continuous collection of science data for a period of time with fixed  Telescope Targets  and configuration. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=30025}{CTA-GLOS-286}})}, 
    first={Observation (Science)}, 
}

\newglossaryentry{Science Alert}{
    name={Science Alert}, 
    description={Filtered  Candidate Science Alerts  that have passed the associated trigger criteria and are suitable either for CTA Observations or issuing to external observatories. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=30026}{CTA-GLOS-287}})}
}

\newglossaryentry{Candidate Science Alert}{
    name={Candidate Science Alert}, 
    description={Incoming notifications of potentially interesting scientific events either from external observatories or generated by the alert pipeline for internal consideration, that will be checked against trigger criteria to determine whether this becomes a  Science Alert . ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=30027}{CTA-GLOS-288}})}
}

\newglossaryentry{Long-term Schedule}{
    name={Long-term Schedule}, 
    description={Based on scientific proposals, the Long-Term Schedule allocates time under a perfect operation scenario, on timescales from yearly down to monthly, taking into account the expected CTA duty cycle. Long-term scheduling is performed by the Science User Support System. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=30029}{CTA-GLOS-290}})}
}

\newglossaryentry{Mid-term Schedule}{
    name={Mid-term Schedule}, 
    description={Based on the Long-Term Schedule, the mid-term schedule takes planned maintenance and calibration activities into account, on timescales from monthly down to daily. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=30030}{CTA-GLOS-291}})}
}

\newglossaryentry{Short-term Schedule}{
    name={Short-term Schedule}, 
    description={Based on the Mid-term Schedule, the Short-term Schedule is activated each day prior to Observations commencing, incorporating Science Alerts and telescope availability during the night, operating in real time. Short-term scheduling is performed by the Observation Execution System. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=30031}{CTA-GLOS-292}})}
}

\newglossaryentry{Air-Shower Event}{
    name={Air-Shower Event}, 
    description={Incident in which Cherenkov light from an atmospheric particle cascade is identified using one or more Cherenkov Telescopes. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=27940}{CTA-GLOS-192}})}
}

\newglossaryentry{Array-Level Event}{
    name={Array-Level Event}, 
    description={A single Air-Shower Event Triggering multiple Cherenkov Cameras and judged suitable for storage. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=27941}{CTA-GLOS-193}})}
}

\newglossaryentry{Observing Night}{
    name={Observing Night}, 
    description={A night during which environmental and system conditions are suitable for  Science Observations  to take place, with operations following a defined cycle. The Observing Night starts at sunset and finishes at sunrise. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=30018}{CTA-GLOS-279}})}
}

\newglossaryentry{Support Astronomer}{
    name={Support Astronomer}, 
    description={Supports on-site science operations including scheduling of observations, data quality monitoring, and the handling of  Science Alerts . ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=30028}{CTA-GLOS-289}})}
}

\newglossaryentry{Available}{
    name={Available}, 
    description={A system is considered to be available if it is capable of providing all of the required functions with the required performance under the appropriate conditions over a given time interval, assuming that any required external resources are provided. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=29427}{CTA-GLOS-269}})}
}

\newglossaryentry{Logs}{
    name={Logs}, 
    description={Logs are records of events that occur in the software elements (of the ACADA/Telescope/Controllable Systems). Events that cause logs are, among others:  Errors ,  Alarms  and usual software operations. Logs have different levels. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31058}{CTA-GLOS-297}})}
}

\newglossaryentry{Trace logs}{
    name={Trace logs}, 
    description={Messages indicating a function-calling sequence. Trace logs are generated whenever a function is entered and are used to report calls to a function. They are used to build call trees during very critical debugging situations. The amount of TRACE logs can be huge and will very likely affect the performance of the system substantially. TRACE logging should be switched on only in very particular situations and for a short amount of time. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31059}{CTA-GLOS-298}})}
}

\newglossaryentry{Delouse Logs}{
    name={Delouse Logs}, 
    description={A lower level than DEBUG, just to allow the finer tuning. Generally same meaning as DEBUG. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31060}{CTA-GLOS-299}})}
}

\newglossaryentry{Debug Logs}{
    name={Debug Logs}, 
    description={Messages that contain information normally of use only when debugging a program. Such logs are therefore normally only interesting for software engineers. Analysis of DEBUG logs should take place only while investigating problems and can put a substantial load on the system. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31061}{CTA-GLOS-300}})}
}

\newglossaryentry{Info Logs}{
    name={Info Logs}, 
    description={Informational messages. This log level is used to publish information of interest during the normal operation of the system. This information is directed to operators, engineers or anybody else working with the system. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31062}{CTA-GLOS-301}})}
}

\newglossaryentry{Notice Logs}{
    name={Notice Logs}, 
    description={Conditions that are not error conditions, but that may require special handling. These logs are used to catch the attention of people (normally operators or software engineers) looking at the logging output. They denote important situations in the system, but not necessarily error or fault conditions. A NOTICE logging level should be selected with care because many NOTICE messages weaken the attention of the reader. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31063}{CTA-GLOS-302}})}
}

\newglossaryentry{Warning Logs}{
    name={Warning Logs}, 
    description={Warning messages. These logs are used to report to readers (normally operators or software engineers) conditions that are not errors but that could lead to errors or problems. A WARNING logging level should be selected with care because many WARNING messages weaken the attention of the reader. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31064}{CTA-GLOS-303}})}
}

\newglossaryentry{Error Logs}{
    name={Error Logs}, 
    description={Error messages. They are normally generated by the system when an Error (see below) happens and not explicitly used in applications by calling the logging API. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31065}{CTA-GLOS-304}})}
}

\newglossaryentry{Critical Logs}{
    name={Critical Logs}, 
    description={Critical logs denote an Alarm condition that shall be reported to operators, such as hard device errors. They are normally generated by the Alarm System and not explicitly used in applications by calling the logging API ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31066}{CTA-GLOS-305}})}
}

\newglossaryentry{Alert Logs}{
    name={Alert Logs}, 
    description={A condition that should be corrected immediately, such as a corrupted system database. Alert logs denote an Alarm condition that shall be reported to operators. This denotes a problem more important than Critical. They are normally generated by the Alarm System and not explicitly used in applications by calling the logging API. Alerts are used for reporting errors that must be solved immediately. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31067}{CTA-GLOS-306}})}
}

\newglossaryentry{Emergency Logs}{
    name={Emergency Logs}, 
    description={Emergency logs denote an Alarm condition of the highest priority, a panic condition that must be solved immediately. This is normally broadcast to all users. They are normally generated by the Alarm System and not explicitly used in applications by calling the logging API. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31068}{CTA-GLOS-307}})}
}

\newglossaryentry{logging}{
    name={logging}, 
    description={(Off) Level not to be used for actual logging, but to set log levels for filtering. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31069}{CTA-GLOS-308}})}, 
    first={Off (logging)}, 
}

\newglossaryentry{Alarm}{
    name={Alarm}, 
    description={A problem or condition that should be reported to the operator and may require their action. In addition, the alarm event is logged. Alarms can have different severity levels. This could match the log levels  CRITICAL, ALERT & EMERGENCY , or be finer grained. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31070}{CTA-GLOS-309}})}
}

\newglossaryentry{software}{
    name={software}, 
    description={(Error) A problem that is encountered when a program is being executed. Runtime errors can occur in software environments for many different reasons; for example, peripheral devices may not be turned on, or instructions may be invalid. ACADA errors are to be handled, solved if possible, and reported to the operator if not, but in any case always logged using the logging system as  ERROR  logs. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31071}{CTA-GLOS-310}})}, 
    first={Error (software)}, 
}

\newglossaryentry{Emergency stop button}{
    name={Emergency stop button}, 
    description={A red mushroom-headed button that, when activated, will immediately start the emergency stop sequence. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31117}{CTA-GLOS-350}})}
}

\newglossaryentry{E-Stop}{
    name={E-Stop}, 
    description={(Emergency stop) An E-Stop is a function that is intended to avert harm or to reduce existing hazards to persons, machinery, or work in progress. E-Stop is not a safeguard but is considered to be a complementary protective measure. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31116}{CTA-GLOS-349}})}, 
    first={Emergency stop (E-Stop)}, 
}

\newglossaryentry{DET}{
    name={DET}, 
    description={(Detection Ranking) DET is a relative numerical scale estimating the effectiveness of the controls to prevent or detect the cause or failure mode before the failure reaches the customer. The assumption is that the cause has occurred. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31114}{CTA-GLOS-347}})}, 
    first={Detection Ranking (DET)}, 
}

\newglossaryentry{OCC}{
    name={OCC}, 
    description={(Occurrence Ranking) OCC is a relative numerical scale estimating the probability that the cause, if it occurs, will produce the failure mode and its particular effect. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31113}{CTA-GLOS-346}})}, 
    first={Occurrence Ranking (OCC)}, 
}

\newglossaryentry{Emergency situation}{
    name={Emergency situation}, 
    description={An immediately hazardous situation that needs to be ended or averted quickly in order to prevent injury or damage. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31115}{CTA-GLOS-348}})}
}

\newglossaryentry{SEV}{
    name={SEV}, 
    description={(Severity Ranking) SEV is a relative numerical scale estimating how severe the end user (customer) will perceive the Effect of a failure. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31112}{CTA-GLOS-345}})}, 
    first={Severity Ranking (SEV)}, 
}

\newglossaryentry{Reliability}{
    name={Reliability}, 
    description={The probability that an item or system can perform a required function under given conditions for a given time interval. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31111}{CTA-GLOS-344}})}
}

\newglossaryentry{RPN}{
    name={RPN}, 
    description={(Risk Priority Number) The RPN is a number which quantifies the risk and the impact of failures modes.  The RPN is obtained as the product between 'Severity', 'Occurrence' and 'Detection' Ranking numbers. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31110}{CTA-GLOS-343}})}, 
    first={Risk Priority Number (RPN)}, 
}

\newglossaryentry{MLT}{
    name={MLT}, 
    description={(Maintenance Logistic Time) MLT is the time not associated with the Corrective Maintenance work itself (i.e. time for the maintenance technician to prepare work, to order or to obtain spares or special tools if not available on site etc.). ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31109}{CTA-GLOS-342}})}, 
    first={Maintenance Logistic Time (MLT)}, 
}

\newglossaryentry{Preventive Maintenance}{
    name={Preventive Maintenance}, 
    description={The maintenance carried out at pre-determined intervals or according to prescribed criteria and intended to reduce the probability of failure or the degradation of the functioning of an item. This shall include First, Second and Third Line Maintenance. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31108}{CTA-GLOS-341}})}
}

\newglossaryentry{MPH/OH}{
    name={MPH/OH}, 
    description={(Maintenance Person-Hours per Operating Hour) The total number of Person-Hours expended divided by the total Operating Hours. Note that MPH/OH is expressed in Maintenance Person-Hours per million Operating Hours. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31107}{CTA-GLOS-340}})}, 
    first={Maintenance Person-Hours per Operating Hour (MPH/OH)}, 
}

\newglossaryentry{MPH}{
    name={MPH}, 
    description={(Maintenance Person-Hours) The sum of the individual task hours to: troubleshoot, fault isolate, replace, align or adjust and function check, multiplied by the number of personnel required to do each task. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31106}{CTA-GLOS-339}})}, 
    first={Maintenance Person-Hours (MPH)}, 
}

\newglossaryentry{MLC}{
    name={MLC}, 
    description={(Maintenance Labour Cost) The sum of all direct ACMT cost per unit measure and the direct Preventive Maintenance per unit measure. Note: The unit measure may be per hour, calendar time, kilometre, etc. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31105}{CTA-GLOS-338}})}, 
    first={Maintenance Labour Cost (MLC)}, 
}

\newglossaryentry{Maintenance}{
    name={Maintenance}, 
    description={All activities necessary to keep an asset in, or restore it to a specified condition, keep it safe, reliable and fit for service throughout the operational lifecycle phase. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31104}{CTA-GLOS-337}})}
}

\newglossaryentry{MTTF}{
    name={MTTF}, 
    description={(Mean Time to Failure) The average time an item is expected to work before a failure occurs. MTTF is a reliability measure for non-repairable systems/components. MTTF is calculated as the total operating hours during a specific interval of time divided by the total number of confirmed failure during that same interval of time. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31103}{CTA-GLOS-336}})}, 
    first={Mean Time to Failure (MTTF)}, 
}

\newglossaryentry{MTBF}{
    name={MTBF}, 
    description={(Mean Time Between Failures) The average time an item is expected to work before a failure occurs. MTBF is a reliability measure for repairable systems/components. MTBF is calculated as the total operating hours during a specific interval of time divided by the total number of confirmed failure during that same interval of time. Alternately, MTBF is also known as the reciprocal of the Failure Rate. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31102}{CTA-GLOS-335}})}, 
    first={Mean Time Between Failures (MTBF)}, 
}

\newglossaryentry{MTTR}{
    name={MTTR}, 
    description={(Mean Time to Repair) MTTR can be stated, at a given level of maintenance, as the average repair time for individual faults over the life of the equipment. MTTR may include response time (where applicable), diagnostics and rectification of the failure (including software reboot) up to the point that the system is restored to full functionality. In the event that the failure of an item of equipment cannot be rectified, this time measurement includes the time necessary to remove the failed item and replace it with a functioning one. Note: Maintenance Logistic Time required to obtain any special tools or spares is excluded. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31101}{CTA-GLOS-334}})}, 
    first={Mean Time to Repair (MTTR)}, 
}

\newglossaryentry{LLRU}{
    name={LLRU}, 
    description={(Lowest Level Replaceable Unit) The LLRU is the smallest faulty unit the maintenance personnel can identify and isolate at all levels of maintenance within a given Mean Time to Repair (the smallest part of an item that can be replaced to provide an effective repair). Repairs of LLRUs will be undertaken in the specialized workshop. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31100}{CTA-GLOS-333}})}, 
    first={Lowest Level Replaceable Unit (LLRU)}, 
}

\newglossaryentry{LRU}{
    name={LRU}, 
    description={(Line Replaceable Unit) The LRU is the smallest faulty unit the maintenance personnel can identify and correct at the First Level of Maintenance to restore system availability within a given Mean Time to Repair (MTTR). Each LRU should be designed for ease of replacement and fault isolation. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31099}{CTA-GLOS-332}})}, 
    first={Line Replaceable Unit (LRU)}, 
}

\newglossaryentry{TLM}{
    name={TLM}, 
    description={(Third Level Maintenance) If testing, repairing or replacement of a faulty LRU/LLRU, requires specialized skills or test equipment and facilities (typically at manufacturer's site). ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31098}{CTA-GLOS-331}})}, 
    first={Third Level Maintenance (TLM)}, 
}

\newglossaryentry{SLM}{
    name={SLM}, 
    description={(Second Level Maintenance) If testing, repairing or replacement of a faulty LRU/LLRU, has to be undertaken in a specialized workshop on site. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31097}{CTA-GLOS-330}})}, 
    first={Second Level Maintenance (SLM)}, 
}

\newglossaryentry{FLM}{
    name={FLM}, 
    description={(First Level Maintenance) FLM is the maintenance procedure, usually at the location of the failure which consists of diagnosis, recovery of the diagnosis made by the system and possibly its analysis, LRU's/LLRU's replacement and final functional test. This procedure is designed to return the system to service in minimum time, using minimum specialized tools. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31096}{CTA-GLOS-329}})}, 
    first={First Level Maintenance (FLM)}, 
}

\newglossaryentry{C}{
    name={C}, 
    description={(Failure Modes, Effects A) An extension of FMEA in which the "criticality" of the effects is also assessed (identifying risk associated with those failure modes, ranking issues in terms of importance and carrying out corrective actions to address the most serious concerns). ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31095}{CTA-GLOS-328}})}, 
    first={Failure Modes, Effects A (C)}, 
}

\newglossaryentry{FMEA}{
    name={FMEA}, 
    description={(Failure Mode and Effects Analysis) A reliability evaluation and design review methodology to analyse system design and performance to determine the effects of each potential failure mode on the system. FMEA uses inductive logic (a process of finding explanations) on a "bottom up" system analysis.  Information developed in this procedure is integrated with reliability, logistics, operations, maintainability and troubleshooting procedures. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31094}{CTA-GLOS-327}})}, 
    first={Failure Mode and Effects Analysis (FMEA)}, 
}

\newglossaryentry{Systematic Failure}{
    name={Systematic Failure}, 
    description={An equipment failure due to an error in the specification, design, construction, installation, operation or maintenance. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31093}{CTA-GLOS-326}})}
}

\newglossaryentry{OAF}{
    name={OAF}, 
    description={(Observing Affecting Failure) A system failure, which causes an interruption of the Observing time. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31092}{CTA-GLOS-325}})}, 
    first={Observing Affecting Failure (OAF)}, 
}

\newglossaryentry{SPF}{
    name={SPF}, 
    description={(Single Point of Failure) A failure of a single item which can result in the failure of the system and it is not compensated for by redundancy or alternative operational procedures. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31091}{CTA-GLOS-324}})}, 
    first={Single Point of Failure (SPF)}, 
}

\newglossaryentry{Human Error}{
    name={Human Error}, 
    description={A human action (mistake), which can result in unintended system behaviour/failure. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31090}{CTA-GLOS-323}})}
}

\newglossaryentry{Error}{
    name={Error}, 
    description={A deviation from the intended design which could result in unintended system behaviour or failure.  Note: This definition is usually applicable in reliability discussions and assessments to make a difference between two terms "failure" and "error". This term could have a different meaning in some other fields (i.e. Software). ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31089}{CTA-GLOS-322}})}
}

\newglossaryentry{Fault}{
    name={Fault}, 
    description={An abnormal condition that could lead to a failure in a system. A fault can be random or systematic. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31088}{CTA-GLOS-321}})}
}

\newglossaryentry{FR}{
    name={FR}, 
    description={(Failure Rate) The number of failures expected in a given interval of time. Failure rates are usually expressed in failures per million operating hours.For constant failure rate items (i.e. exponentially distributed failures), the failure rate is the numerical inverse (the reciprocal) of the Mean Time Between Failures (MTBF). ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31087}{CTA-GLOS-320}})}, 
    first={Failure Rate (FR)}, 
}

\newglossaryentry{Failure}{
    name={Failure}, 
    description={A failure is any incident, malfunction, intermittent condition or a deviation from the specified performance of equipment that prevents it from performing its intended functions or requires manual intervention for safe operation. A failure is considered independent when it is not caused by the malfunction of other equipment, component abuse or incorrect maintenance procedure. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31086}{CTA-GLOS-319}})}
}

\newglossaryentry{Downtime}{
    name={Downtime}, 
    description={The interval of time from the declaration of an Observing Affecting Failure (OAF) to the time that service is fully restored (considering only Observing State time). ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31085}{CTA-GLOS-318}})}
}

\newglossaryentry{Degraded Mode}{
    name={Degraded Mode}, 
    description={A system condition with a known but reduced level of functionality in which the System continues to operate, following fault detection and reaction, or when manually selected. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31084}{CTA-GLOS-317}})}
}

\newglossaryentry{CM}{
    name={CM}, 
    description={(Corrective Maintenance) The maintenance carried out after a fault recognition and intended to put a product into a state in which it can perform a required function. A CM can be postponed (see DCM) or trigger an emergency (see ECA). ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31083}{CTA-GLOS-316}})}, 
    first={Corrective Maintenance (CM)}, 
}

\newglossaryentry{Common Cause Failure}{
    name={Common Cause Failure}, 
    description={An issue that can cause multiple failures across the system. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31082}{CTA-GLOS-315}})}
}

\newglossaryentry{ECA}{
    name={ECA}, 
    description={(Emergency Corrective Action) Emergency Corrective Action is when immediate and rapid corrective action is taken, if a breakdown may have consequences for safety or equipment availability, or may have high economic impact. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31081}{CTA-GLOS-314}})}, 
    first={Emergency Corrective Action (ECA)}, 
}

\newglossaryentry{DCM}{
    name={DCM}, 
    description={(Deferred Corrective Maintenance) All Corrective Maintenance actions that are postponed. For any system breakdown the corrective action can be postponed (becoming a DCM) or a decision may be taken to implement Emergency Corrective Actions (ECA). ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31080}{CTA-GLOS-313}})}, 
    first={Deferred Corrective Maintenance (DCM)}, 
}

\newglossaryentry{Availability}{
    name={Availability}, 
    description={The ability of an item or system to be in a state to perform a required function under given conditions over a given time interval assuming that the required external resources are provided. Generally, the Availability is defined by the formula A = (Uptime) / (Uptime + Downtime), where "Uptime" is the total time that the system is performing required functions and "Downtime" is the time where the system is not able to perform (can include the "time off" if corrective maintenance activities are deferred to be performed during daytime, or "MTTR" if corrective maintenance activities can be done during night in safe conditions, see ECA). ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31079}{CTA-GLOS-312}})}
}

\newglossaryentry{ACMT}{
    name={ACMT}, 
    description={(Active Corrective Maintenance Time) The direct time spent by maintenance personnel after the arrival at the location of a failure; to troubleshoot, isolate the fault, repair and complete a functional check and verify that the equipment has been restored to operational status. The ACMT assumes that all documentation, spare parts and minimum required tools and test equipment for First Level Maintenance are available at the specialized workshop on site; Note: Maintenance Logistic Time required to obtain any of above items is excluded from the ACMT. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31078}{CTA-GLOS-311}})}, 
    first={Active Corrective Maintenance Time (ACMT)}, 
}

\newglossaryentry{NSB}{
    name={NSB}, 
    description={Night Sky Background (Light) ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28369}{CTA-GLOS-229}})}
}

\newglossaryentry{pe}{
    name={pe}, 
    description={photoelectrons(s) ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28481}{CTA-GLOS-241}})}
}

\newglossaryentry{rms}{
    name={rms}, 
    description={Root-mean-square ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=28482}{CTA-GLOS-242}})}
}

\newglossaryentry{Primary Care}{
    name={Primary Care}, 
    description={Also known as first aid, the provision of initial care for an illness or injury. Primary care level capability can be said to exist if an individual is present who holds a first aid qualification covering the following aspects: 1) preservation of life, 2) prevention of further harm and 3) promotion of recovery. ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=29040}{CTA-GLOS-267}})}
}

\newglossaryentry{GTI}{
    name={GTI}, 
    description={Good Time Interval ({\href{https://jama.cta-observatory.org/perspective.req?projectId=11&docId=31295}{CTA-GLOS-358}})}
}
